import type { PeerEntry, VMDetailResponse } from '@/types/api'
import { formatBytes } from './utils'

const APP_VERSION = (import.meta.env.VITE_APP_VERSION as string | undefined) ?? '1.3.0'

export function vmToMarkdown(vmName: string, data: VMDetailResponse): string {
  const { vm, inbound, outbound, top_peers, deny_summary } = data

  const totalIn = inbound.reduce((s, f) => s + f.bytes_src_to_dest + f.bytes_dest_to_src, 0)
  const totalOut = outbound.reduce((s, f) => s + f.bytes_src_to_dest + f.bytes_dest_to_src, 0)
  const totalBytes = totalIn + totalOut
  const denied = [...inbound, ...outbound].filter((f) => f.flow_type === 'Denied')
  const denyRate =
    inbound.length + outbound.length > 0
      ? ((denied.length / (inbound.length + outbound.length)) * 100).toFixed(1)
      : '0'

  const lines: string[] = [
    `## ${vmName}`,
    '',
    `- **IP**: ${vm.ip || '—'}`,
    `- **Subnet**: ${vm.subnet || '—'}`,
    `- **VNet**: ${vm.vnet || '—'}`,
    `- **Peers**: ${top_peers.length}`,
    `- **Total bytes (24h)**: ${formatBytes(totalBytes)}`,
    `- **Deny rate**: ${denyRate}%`,
    '',
  ]

  // Top peers (VM peers only)
  const vmPeers = top_peers.filter((p: PeerEntry) => p.peer_vm)
  if (vmPeers.length > 0) {
    lines.push('### Top peers')
    vmPeers.slice(0, 5).forEach((p, i) => {
      lines.push(`${i + 1}. ${p.peer_vm || p.peer_ip} — ${formatBytes(p.bytes_total)}`)
    })
    lines.push('')
  }

  // Recent denies
  if (denied.length > 0) {
    lines.push('### Recent denies')
    denied.slice(0, 5).forEach((f) => {
      lines.push(`- ${f.src_ip} → ${f.dest_ip}${f.dest_port ? `:${f.dest_port}` : ''} (${f.protocol}${f.acl_rule ? `, rule: ${f.acl_rule}` : ''})`)
    })
    lines.push('')
  }

  // Top deny rules
  if (deny_summary.top_rules.length > 0) {
    lines.push('### Top deny rules')
    deny_summary.top_rules.forEach((r) => lines.push(`- ${r}`))
    lines.push('')
  }

  const url = `${window.location.origin}/vm/${encodeURIComponent(vmName)}`
  lines.push(`---`)
  lines.push(`*Generated by AzureNetMap v${APP_VERSION} at ${new Date().toISOString()}*`)
  lines.push(`*Source: ${url}*`)

  return lines.join('\n')
}
